name = "opendiro-io"
type = "javascript"
account_id = "890d8560bac6cfb5071fe981277b1fad"

workers_dev = true

compatibility_flags = []
compatibility_date = "2022-03-28"

vars = { ENVIRONMENT = "dev" }

[env.dev]
vars = { ENVIRONMENT = "dev" }
workers_dev = true


[env.staging]
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.production]
zone_id = "14802ed20cd89963a2377c8f0de8e312"
routes = [
  "https://opendiro.io/*",
]

vars = { ENVIRONMENT = "production" }



[site]
bucket = "./public"
entry-point = "."

[build]
command = "yarn build"

[build.upload]
format="service-worker"
